
name: Sync WeRead Notes
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Sync WeRead Notes
        env:
          WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: |
          npm install
          npm run sync
    